#!/bin/bash
#SBATCH -N 16 --tasks-per-node=16
#SBATCH --mail-type=ALL
#
# Setup the module command
set echo
set -x 
source /usr/share/Modules/init/bash
# Load the needed modules
module load fftw
#

cd $SLURM_SUBMIT_DIR
echo "$SLURM_NPROCS=" $SLURM_NPROCS
export BINDIR=/share/cluster/RHEL6.2/x86_64/apps/NAMD/2.9/Linux-x86_64-MPI-icc/bin

mpirun -np $SLURM_NPROCS $BINDIR/namd2 +pemap 0-15 prod10.conf > prod10.log
